import type { Metadata } from "next";
import SidePanel from "@/components/sidepanel";
// import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { Menu } from "lucide-react";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children
}: any) {
  return (
    <html lang="en" data-theme={"light"}>
      <body
        className={`antialiased`}
      >
        <div className="min-h-screen bg-[#f8f9f6] text-[#1c1c1c]">
          {/* Header */}
          <header className="flex items-center justify-between px-6 py-4 bg-[#eef3ea] border-b border-[#d2e3c8]">
            <div className="flex items-center gap-3">
              <Menu className="w-6 h-6 text-[#6e8c6f]" />
              <span className="text-xl font-semibold text-[#446442]">Dua & Ruqyah</span>
            </div>
            <button className="btn btn-primary">Export to PDF</button>
          </header>


          {/* Layout */}
          <div className=" grid grid-cols-12">
            {/* Sidebar */}
            <aside className="col-span-3 bg-base-300">
              <SidePanel />
            </aside>

            {/* Main Content */}
            <main className="col-span-9 p-6 space-y-6">
              {children}
            </main>
          </div>

        </div>
      </body>
    </html >
  );
}
